# **혈압 데이터를 사용한 벡터 변환 실습**

In [1]:
!pip install koreanize_matplotlib
import koreanize_matplotlib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss, accuracy_score

Collecting koreanize_matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl.metadata (992 bytes)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from koreanize_matplotlib) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize_matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize_matplotlib) (1.17.0)
Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 84.0 MB/s eta 0:00:00
Installing collected packages: koreanize_matplotlib
Successfully installed koreanize_matplotlib-0.1.1

In [3]:
df=pd.read_csv("혈압.csv", encoding='cp949')
df

     나이  체중    키  수면시간   혈압
0    45  57  152     8  134
1    48  57  152     7  128
2    46  57  152     4  134
3    39  57  152     7  129
4    64  57  152     4  136
..   ..  ..  ...   ...  ...
995  24  46  155     9  123
996  50  47  157     4  133
997  59  47  157     5  135
998  26  47  157     6  129
999  20  45  155     7  120

[1000 rows x 5 columns]

In [4]:
# 입력과 타깃 지정
X=df[['나이', '체중', '키', '수면시간']]  # 입력
y=df['혈압']                              # 타깃
X

     나이  체중    키  수면시간
0    45  57  152     8
1    48  57  152     7
2    46  57  152     4
3    39  57  152     7
4    64  57  152     4
..   ..  ..  ...   ...
995  24  46  155     9
996  50  47  157     4
997  59  47  157     5
998  26  47  157     6
999  20  45  155     7

[1000 rows x 4 columns]

In [7]:
# 파라미터 무작위 추출 후 출력
w1=np.random.normal(size=(4, 2)); print("w1"); print(w1); print()
w2=np.random.normal(size=(2, 1)); print("w2"); print(w2); print()
b1=np.random.normal(1); print("b1"); print(b1); print()
b2=np.random.normal(1); print("b2"); print(b2); print()

# 선형 변환 1
x1 = X @ w1 + b1

# 선형 변환 2
y_pred = x1 @ w2 + b2
print("예측값(y_pred)")
print(y_pred)
print()

# 손실 계산
MSE = np.mean((y_pred-y)**2)
print("평균제곱오차 = ", MSE)

w1
[[ 0.24809731 -1.21781045]
 [-1.88302393 -0.11376082]
 [-0.35755147 -1.46785466]
 [-1.27712291  0.3838326 ]]

w2
[[ 0.77514883]
 [-0.97675364]]

b1
2.169771159076947

b2
-0.7491938328988781

예측값(y_pred)
              0
0    149.010741
1    154.521051
2    155.852035
3    142.084733
4    180.724672
..          ...
995  136.931108
996  180.647247
997  191.718695
998  144.753991
999  135.482104

[1000 rows x 1 columns]

평균제곱오차 =  868.6370907646171

### 이 코드를 반복 실행하면, 파라미터가 바뀌고 예측값 및 손실이 바뀝니다.

### 여기에 경사하강법 코드를 추가하면 파라미터 최적화를 할 수 있습니다.